<?php

return [
    'barangays' => [
        'I-A (Sambat)',
        'I-B (City Sub Riverside)',
        'I-C (Bagong Bayan)',
        'II-A (Triangulo/ Guadalupe 2)',
        'II-B (Guadalupe 1)',
        'II-C (Unson)',
        'II-D (Bulante)',
        'II-E (San Anton)',
        'II-F (Villa Rey)',
        'III-A (Hermanos Belen)',
        'III-B',
        'III-C (Labak/De Roma)',
        'III-D (Villongco)',
        'III-E',
        'III-F (Balagtas)',
        'IV-A',
        'IV-B',
        'IV-C',
        'V-A',
        'V-B',
        'V-C',
        'V-D',
        'VI-A (Mavenida)',
        'VI-B (Sabang Mabini)',
        'VI-C (Bagong Pook)',
        'VI-D (Lakeside)',
        'VI-E (YMCA)',
        'VII-A (P.Alcantara)',
        'VII-B',
        'VII-C',
        'VII-D',
        'VII-E',
        'Atisan',
        'Bautista',
        'Concepcion (Bunot)',
        'Del Remedio (Wawa)',
        'Dolores',
        'San Antonio 1 (Balanga)',
        'San Antonio 2 (Sapa)',
        'San Bartolome (Matang-ag)',
        'San Buenaventura (Palakpakin)',
        'San Crispin (Lumbangan)',
        'San Cristobal',
        'San Diego (Tiim)',
        'San Francisco (Calihan)',
        'San Gabriel (Butucan)',
        'San Gregorio',
        'San Ignacio',
        'San Isidro (Balagbag)',
        'San Joaquin',
        'San Jose (Malamig)',
        'San Juan (Putol)',
        'San Lorenzo (Saluyan)',
        'San Lucas 1 (Malinaw)',
        'San Lucas 2 (Malinaw)',
        'San Marcos (Tikew)',
        'San Mateo (Imok)',
        'San Miguel (Balatuin)',
        'San Nicolas (Mag-ampon)',
        'San Pedro',
        'San Rafael (Buluburan)',
        'San Roque (Sambat)',
        'San Vicente',
        'Santa Ana',
        'Santa Catalina (Sandig)',
        'Santa Cruz (Putol)',
        'Santa Elena',
        'Santa Filomena (Banlagin)',
        'Santa Isabel',
        'Santa Maria',
        'Santa Maria Magdalena (Boe / Kuba)',
        'Santa Monica',
        'Santa Veronica (Bae)',
        'Santiago I (Bulaho)',
        'Santiago II (Bulaho)',
        'Santisimo Rosario (Balagbag)',
        'Santo Angel (Ilog)',
        'Santo Cristo',
        'Santo Niño (Arsum)',
        'Soledad (Macopa)',
    ],
];
